export const Paragraphs = [
  "early to bed and early to rise keeps a man healthy wealthy and wise the great advantage of early rising is the good start it gives us in our days work in the early morning the mind is fresh and there are few sounds so that work done at that time is generally well donethe early riser also finds time to take some exercise in the fresh morning air and this exercise supplies him with a fund of energy that will last until the evening by beginning so early he knows that he has plenty of time to do thorough all the work he can be expected to do and is not tempted to hurry over any part of it",
  "books are the store of knowledge and wisdom they contain variety of pleasures reading books makes our mind strong and broaden our outlook reading of books gives us a great pleasure they are the best friends of manthrough books we come to know our civilizationthrough books we come into contact with great scholars poets and philosophers books never misguide us they help us in building our character by reading books our sadness is removed if we are on a long journey books give us a good company everyone therefore should develop the habit of reading books",
  "the bird i like most is the parrot the parrot is a very beautiful bird its feathers are green it has a red beak its beak is curved round the neck of a parrot there are black rings overall it is a lovely looking bird it eats grains fruits leaves seeds pears nuts mangoes and boiled rice etcthe parrot is a talking bird it can imitate the human voice it is found in almost all the warm countries it generally lives in the hollows of trees some people keep it in a small cage which is not good some people train parrots to do wonderful things",
  "some people think that the aim of education is merely to give ledge these people want students to read books books books and do nothing else but add to their knowledge others believe that knowledge alone is enough only that which enables a man to earn his living can be called education such people think that bread is more important than-anything else still others believe that education should aim solely at making good citizens and good patriotsall these people see only one of the several purposes of education as a matter of fact education should aim at all these three things together",
  "the atmosphere is a transparent envelope of gases and suspended particles that surround the earth without chemical processes involving several of the atmospheric gases life could not exist even the physical processes that operate in the atmosphere are of vital importance because they are responsible for the earth varied climates the atmosphere is composed almost entirely of oxygen and nitrogenthe atmosphere is the source of every living thing in the world it plays a very important role in serving the worlds needs it provides ventilation to the earth",
  "health is a state of complete physical social and mental well being and not merely the absence of disease or infirmity health is thus a level of functional efficiency of living beings and a general condition of a persons mind body and spirit meaning it is free from illness injury and pain it is a resource of everyday life and a positive concept emphasizing physical capabilitiesgood health is a secret of every happy man there is an old saying health is wealth staying healthy for children is vital for proper growth and development of mind and body",
  "water is one of the natures precious gifts to mankind all living things consist mostly of water eg the human body is of two thirds of water it is clear colourless liquid that appears blue when viewed through a thickness of 20 ft the colour reflects not only from physical causes but also from suspended impurities the freezing point of water is 0degree centigrade and its boiling point is 100 degree centigradewater is the most essential component of life and is vital for sustenance the importance of water is it helps in specific metabolic tasks and regulates our body temperature",
  "the india gate  is the national monument of india it is in new delhi india gate was designed by sir edwin lutyens it was built in 1931 the 42-metre tall india gate is situated in such a way that many important roads spread out from it is built of red sandstone and granite originally known as the all india war memorial it is a prominent landmark in delhi and commemorates the 90000 soldiers of the indian army who lost their lives while fighting for the indian empire or more correctly the british raj in world war i and the third anglo-afghan war",
  "it is one thing to own a library it is quite another to use it wisely i have often been astonished how little care people devote to the selection of what they readbooks we know are almost innumerable our hours of reading are alas! very few and yet many people read almost by hazard they will take any book they chance to find in a room at a friends house they will buy a novel at a railway stall if it has an attractive title ndeed i believe in some cases even the binding affects that choice",
  "indian culture is the mother of all cultures be it art of living or apparently the rich knowledge of science and music all the regions and religions of the world have their own culture with many customs traditions and refined qualities it is a culture of love respect honouring others and humbling ones own ego so that the inner nature which is naturally pure and modest will shine forthrespect and reverence for elders is a key stone of indian culture this genuine acknowledgment of seniority is demonstrated through endering customs",
];
// https//all-essayblogspotcom/2013/04/short-essay-on-indian-culture-200-wordshtml
